name = "DataFramesFunk"
uuid = "fd5d215f-c9e8-4d96-b990-45c66a23d446"
authors = ["georgeg <georgegi86@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
ShiftedArrays = "1277b4bf-5013-50f5-be3d-901d8477a67a"

[compat]
DataFrames = "1.7.0"
DataFramesMeta = "0.15.4"
ShiftedArrays = "2.0.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
