name = "DataFramesFunk"
uuid = "fd5d215f-c9e8-4d96-b990-45c66a23d446"
authors = ["georgeg <georgegi86@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
